
from dydx3.constants import API_HOST_GOERLI,API_HOST_MAINNET
from decouple import config

'''SELECTED MODE'''
MODE = "DEVELOPMENT"

#Close all position and orders
ABORT_ALL_POSITION = False

#Find cointegrated pair
FIND_COINTEGRATED = True

#Manage exits
MANAGE_EXIT = True

#Place trades
PLACE_TRADES = True

#Timeframe
RESOLUTION = "1HOUR"

#Stat windows
WINDOW = 21

#Threshold opening
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1
USD_PER_TRADE = 100
USD_MIN_COLLATERAL = 1880

#Threshold closing
CLOSE_AT_ZSCORE_CROSS = True

#Ethereum address
ETHEREUM_ADDRESS="0xaD62F821b0Ac7EC2949693b2ACADB5C0ce76BcD7"

#Key production
#Must to be on Mainnet on dydx

STARK_PRIVATE_KEY_MAINNET=config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET=config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_SECRET_MAINNET=config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_PASSPHRASE_MAINNET=config("STARK_PRIVATE_KEY_MAINNET")

#Key development
#Must to be on Testnet on dydx

STARK_PRIVATE_KEY_TESTNET=config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET=config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET=config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET=config("DYDX_API_PASSPHRASE_TESTNET")

#Key Export
STARK_PRIVATE_KEY=STARK_PRIVATE_KEY_MAINNET if MODE=="PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY=DYDX_API_KEY_MAINNET if MODE=="PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET=DYDX_API_SECRET_MAINNET if MODE=="PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE=DYDX_API_PASSPHRASE_MAINNET if MODE=="PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

#Host Export
HOST=API_HOST_MAINNET if MODE=="PRODUCTION" else API_HOST_GOERLI

#HTTP PROVIDER
HTTP_PROVIDER_MAINNET="https://eth-mainnet.g.alchemy.com/v2/3d05jly8pz0Mtpsyo4h3v0eGSqa-NBf-"
HTTP_PROVIDER_TESTNET="https://eth-goerli.g.alchemy.com/v2/t22sruEI1a-8_Ulq0OnFcSRRPoQsaRK0"
HTTP_PROVIDER=HTTP_PROVIDER_MAINNET if MODE=="PRODUCTION" else HTTP_PROVIDER_TESTNET